### ISSUE TITLE
Chinese characters support

### ISSUE THREAD

**Issue by ephen** [mike-ward/Markdown-Edit#153]
Although I can write Chinese in Markdown-Edit, I can't open a file in normal which wrote by other edit program. Just like this:

![](http://ww2.sinaimg.cn/large/5ebd877egw1f4miw3ngh4j20un09zadz.jpg)

The default Chinese character of most edit programs (and browses) is ANSI/OEM GBK, hope to be supported.

**Comment by mike-ward** [comment]
I'm thinking the only sensible thing to do is to add an encoding dropdown in the settings dialog (similar to the line endings dropdown). Feedback anyone?

**Comment by cyotek** [comment]
Window's regional settings has a system locale for non-Unicode programs. I'm assuming that that is in the Registry somewhere so you could pull it out, and if so, could you not map that directly to a code page and then obtain an encoding from that?

Haven't a clue if this is a viable option or not, it was just a random thought. That would probably be nicer than a setting and would just work out the box. In theory.

**Comment by mike-ward** [comment]
Not sure I follow. Sounds like he has documents with different character encodings. Sniffing for the systems locale might make for a nice default but if it doesn't match the document encoding?

**Comment by cyotek** [comment]
True, I assumed that they were documents saved in the default system code page rather than something more specific like UTF-8 (to be frank I don't know much about code pages, as I said it was a random thought and I haven't had to think about them since the days of DOS :)). If multiple documents have content in different code pages then I agree my idea wouldn't work - but then surely neither would yours as it too would be a global option and would still involve having to reconfigure each time you opened a document that was different to that setting.

At the end of the day I guess you will have to simply ask the user in some fashion - I imagine that (even if it's possible) it's really difficult to try and guess encoding (I remember some bug in Notepad a few years back where it tried to guess encoding and turned normal English into Chinese (or similar))

**Comment by ephen** [comment]
I considered the approach to add an encoding dropdown in the settings dialog is used to modify, the better way is sniffing for the right encoding format. And if sniffing failed, use the default one.

**Comment by mike-ward** [comment]
Detecting a charset or encoding is a difficult heuristics probem. As luck would have it, there's a C# implementation of Mozilla's algorithm [here](https://github.com/errepi/ude).

The bigger question is the UI. I've already added and encoding/charset drop-down to the settings dialog. If I add the auto-detect algorithm, it implies that the setting in the dialog is not remembered, because the value in the settings dialog reflects the encoding/charset of the current document.

It's likely the auto-detect won't fail often given it's from Mozilla so maybe it's a moot point. Thoughts?

**Comment by ephen** [comment]
The drop-down setting to transfer encoding for the writing content, not for change the display. 
Or it doesn't need the drop-down setting.
