### ISSUE TITLE
html in markdown source - unexpected results

### ISSUE THREAD

**Issue by the-reverend** [mike-ward/Markdown-Edit#177]
i often add page-break divs in markdown to improve print output, e.g. 

```
<div style="page-break-after:always"></div>
## Next Section
```

it would be great if arbitrary html was passed through to the output without modification.

**Comment by mike-ward** [comment]
Place a blank line in-between. Markdown (and Commonmark) require a blank line to terminate HTML blocks.

**Comment by the-reverend** [comment]
i switched to the multimarkdown parsing engine instead of discount and it works fine.

**Comment by the-reverend** [comment]
strange, multimarkdown doesn't have this requirement. will this render a blank line at the top of the new page?

**Comment by mike-ward** [comment]
That's because mm is not following the standard commonmark spec.

**Comment by the-reverend** [comment]
i can appreciate adherence to standards, but i have a large collection of markdown documents that i have personally authored over the years that have relied on this. it's tedious to revise them all just so i can reliably print using your (potentially great) product.

**Comment by mike-ward** [comment]
One of the reasons CommonMark was initiated was that too many Markdown engines did things differently resulting in "unexpected" behavior. 

MDE does have the capability of running MM since it's a command line program. In the settings file (F9) Set
```
  "CustomMarkdownConverter": "multimarkdown.exe -f",
```
I don't make any warranties about this feature. Currently, there's a bug in the command line parsing that requires that you pass at least one command line parameter (I used -f because it seemed like the appropriate option for MM).

**Comment by mike-ward** [comment]
If you use the full path, you'll need to use the short name. Example:

    "CustomMarkdownConverter":  "c:\\PROGRA~2\\MULTIM~1.0\\bin\\MULTIM~1.EXE -f"

**Comment by the-reverend** [comment]
thanks mike! i'll give it a shot next weekend.
