### ISSUE TITLE
Tabs Fail to Render Correctly

### ISSUE THREAD

**Issue by jvarghe** [mike-ward/Markdown-Edit#201]
![double tab fails to render](https://cloud.githubusercontent.com/assets/13189319/19319399/c0c150e4-907a-11e6-9057-03e8ae46c860.PNG)

If you look at this image, the line with the first (2.) and second (a.) bullet point are displayed correctly, but the third one (i.) does not. This document was prepared in another commonmark editor, but Markdown Edit doesn't display indents correctly.

Why are tabs in MDE only 2 spaces long? Can you please offer a setting to make them 4 spaces long? That is the standard. 

The indentation should look like this: 

![correct identation](https://cloud.githubusercontent.com/assets/13189319/19319645/c3001dc6-907b-11e6-991d-c1221fca2f7b.PNG)

**Comment by mike-ward** [comment]
I do not like tabs in documents. I've lost more hours of my life to tabs screwing up stuff than I can count. 

Tabs are two spaces because four spaces in Markdown indicate an HTML block in many cases.

Even if you could set the tabs to 4, MDE would expand them as spaces when saved.

I simply choose not to support tabs in MDE. They're a pain in my butt to support, I don't like them and therefore MDE does not support them.

If the tone sounds harsh, I don't mean it that way. I do appreciate your bug report (and yes, I acknowledge that it's a bug). But I am firm on this one. If that means you move on to another editor, I get it.

P.S. I'm old enough to remember when 8 spaces was the standard for tabs.

**Comment by jvarghe** [comment]
Markdown Edit is your project, so you are king here. Thanks for considering my request.

**Comment by mike-ward** [comment]
Thanks for understanding. Tabs are sort of a sore spot with me if you hadn't noticed 😄
