### ISSUE TITLE
Wrap lines in outputted markdown file.

### ISSUE THREAD

**Issue by grokys** [mike-ward/Markdown-Edit#22]
Add a line length setting and automatically wrap lines in the outputted .md file to that length. Currently the .md file is saved with each paragraph all on one line, which is not ideal.

**Comment by mike-ward** [comment]
You can format that file by pressing Alt+F or by using the context menus.

There are several issues with reformatting Markdown files. It's more than a matter of just wrapping lines since white space is often significant.

The program presently uses Pandoc to reformat files which does a great job but also does some things that can change the meaning of the text layout. This is not Pandoc's fault, but is due to ambiguities in the Markdown spec.

For these reasons, I'm electing to not add a format-on-save option.

**Comment by grokys** [comment]
Thanks for the reply - I wasn't aware of Alt+F. However, given the limitations of Pandoc, it would be useful if Alt+F just formatted the currently selected text if any, as it's screwing up my code blocks. Let me know and I can open a new issue.

**Comment by mike-ward** [comment]
Go ahead and open a new issue. I was meaning to do this as some point.

Code blocks are one of those places where Pandoc favors writing them as indented instead of fenced. Again, not a bug, a choice. There are other places (like pipe tables), which are commonly used but not supported by Commonmark.

**Comment by grokys** [comment]
I think my main /problem is that I'm writing posts for gihub pages which insists on denoting code block using a `{% highlight csharp %}` syntax which doesn't seem to be recognised.
