### ISSUE TITLE
Loop and memory leak

### ISSUE THREAD

**Issue by dsportes** [mike-ward/Markdown-Edit#225]
When opening this file and clicking in the last line, a memory leak is appearing (memory dramatically increasing in windows 10 task manager) and I must kill the process.
Very strange ! (I love this tool !)
[Forums - API REST-Data.txt](https://github.com/mike-ward/Markdown-Edit/files/691611/Forums.-.API.REST-Data.txt)

**Comment by mike-ward** [comment]
If you open this file in notepad you'll find a bunch of hidden null characters at the end of the document. Remove them and MDE works again. I can't see why this would crash MDE but it does. While technically a bug, I'm closing it because it does not appear to be a normal text file. If you feel otherwise, let me know and I'll examine further.

**Comment by dsportes** [comment]
I just started to add a comment saying that my file unfortunately contains a lot of \0 (after a system crash) ... but you found it faster than me :-)
Many thanks, issue solved (I agree a text file as to be "normal").
