### ISSUE TITLE
Add GitHub Flavored Markdown support

### ISSUE THREAD

**Issue by aloisdg** [mike-ward/Markdown-Edit#25]
Hello,

It would be nice to add a way to use the GitHub Flavored Markown.

Cheers,

**Comment by mike-ward** [comment]
Is there an official Github markdown engine available?

**Comment by aloisdg** [comment]
They are using [Kramdown](https://rubygems.org/gems/kramdown).

[1](https://help.github.com/articles/migrating-your-pages-site-from-maruku/) [2](https://pages.github.com/versions/)

**Comment by mike-ward** [comment]
Ruby and no Abstract Syntax Tree (needed for syntax highlighting). Not a good fit for a .NET application.

Pandoc claims Github flavored Markdown support and does generate AST's. That might be a path but requires running Pandoc on every edit update cycle (twice actually, once for AST, once for HTML output). Not sure I want to go there. I've also found Pandoc to be a bit odd in it's output at time (I hesitate to say buggy since often it's a matter of opinion with Markdown. That's partly why I've stuck with Commonmark)

What features in Github flavored Markdown are you wanting?

**Comment by aloisdg** [comment]
I would love Check boxes and fences.

- [ ] checkbox


```c#

// fences

```

**Comment by mike-ward** [comment]
Fences already exist in Commonmark, albeit without syntax highlighting.

I suspect tables will come shortly after the standard is finalized. There's lots of talk about it.

Not so much on checkboxes.

**Comment by aloisdg** [comment]
Ok well, if you decide to keep following the spec, I can totally understand.
