### ISSUE TITLE
Custom Markdown Engine first line not being rendered: MultiMarkdown.exe

### ISSUE THREAD

**Issue by mmathie** [mike-ward/Markdown-Edit#267]
Hey there, i recently discovered that Markdown Edit supports custom markdown engines and at first I was overjoyed since this means that I can use MultiMarkdown whenever I need footnotes :D

But sadly I discovered an issue:

The first line that is written in Markdown Edit is not parsed in the live preview. Please see the images below for reference:
![Second line and any after that is being rendered correctly](https://user-images.githubusercontent.com/32921815/66188510-b26d6d00-e687-11e9-986e-0ede095067a6.png)
![First line is not rendered correctly](https://user-images.githubusercontent.com/32921815/66188512-b26d6d00-e687-11e9-8c62-8d31ca6d78b3.png)

The first line of the file I am editing is not parsed by into the live preview. No matter what kind of markdown is used.

Versions I am using:
- Markdown Edit Version 1.35
- MultiMarkdown Version 6.4.0

Output of MultiMarkdown.exe --version:
```
MultiMarkdown 6 v6.4.0
Copyright ┬® 2016 - 2018 Fletcher T. Penney.
...
```

My multimarkdown configuration file (relevant lines only):
```
"CustomMarkdownConverter": "D:\\Program Files\\MultiMarkdown 6.4.0\\bin\\multimarkdown.exe",
"CustomMarkdownConverterArgs": "",
```

Additionally, if I parse a file which has markdown in the first line with MultiMarkdown manually it works just fine. `# Heading 1` turns into `<h1 id="1">Heading 1</h1>`

If I copy the HTML output out of Markdown Edit it is exported as `<p>﻿# 1</p>`.  Apparently the first line is **Always** rendered as regular text, regardless of the markdown tags that are present.

If I, on the other hand, put the Markdown on the second line and copy the HTML the following is my output:
```HTML
<p>﻿</p>

<h1 id="1">1</h1>
```

It appears that Markdown Edit puts a single, empty `<p></p>` tag around the contents of the first line, regardless of what the actual content of the line is, only starting the actual parsing afterwards.

**Comment by matmaa15** [comment]
UPDATE:

So, out of pure curiosity I tried to use HTML Tags to try and see what would be generated by ME and MM.exe.

| Input | MarkdownEdit | Multimarkdown.exe |
| --- | --- | --- |
| `<h1>test</h1>`  | `<p>﻿<h1>test</h1></p>` | `<h1>test</h1>` |

This reaffirmed my suspicion that ME simply puts `<p>` tags around whatever it receives as the response for the first line instead of sending it to the Custom Markdown Engine.

Additionally, I tried the following:

| Input | MarkdownEdit | Multimarkdown.exe |
| --- | --- | --- |
| `<!--This is a test-->`  | `<p>﻿<!--This is a test--></p>` | `<!--This is a test-->` |

as well as an empty first line:

| Input | MarkdownEdit | Multimarkdown.exe |
| --- | --- | --- |
|| `<p>﻿</p>` ||


As you can see even though there should be no output at all the `<p>` tags are there.

**Comment by Nefcanto** [comment]
No answer to this after almost two years?

**Comment by mike-ward** [comment]
See README.MD
