### ISSUE TITLE
Possible to export HTML/PDF?

### ISSUE THREAD

**Issue by UweKeim** [mike-ward/Markdown-Edit#29]
Most likely I'm simply blind and did not find the right menu item:

Is it possible to export a HTML document or a PDF document?

Only thing I found is to right click the IE view and select "Print" then print to a locally installed PDF printer.

**Comment by mike-ward** [comment]
No export to PDF. You can export to HTML from the editor. Ctrl+E and Ctrl+Shift+E (see the help in F1 for the difference).

I've shied away from producing output because there are so many tools out there that already do this. Check http://pandoc.org. It can handle all sorts of transformations for generating docs/pdfs.

**Comment by UweKeim** [comment]
Thanks a lot. Maybe [providing options to configure a command line for PDF exporting](http://stackoverflow.com/a/430596/107625) would be a helpful thing.
