### ISSUE TITLE
Keep those icons

### ISSUE THREAD

**Issue by UweKeim** [mike-ward/Markdown-Edit#53]
Every time I ugrade to a newer version, my Windows 10 pinned taskbar icon is no longer valid.

I have to remove it and do a complicated search through my HDD and pin it again.

This is frustrating :cry: 

Can you modify your installer to not "destroy everything" I've configured?

**Comment by mike-ward** [comment]
Yeah, that one bugs me as well. I'll check to see if WiX allows a different behavior.

**Comment by UweKeim** [comment]
Thanks a lot, @mike-ward.

In my MSIs I'm creating, usually using [WixSharp](https://wixsharp.codeplex.com/), just I found a comment:

> The **upgrade code** should stay the same for all subsequent versions of the product that are upgrades to this release.

and

> The **product code** (and the version number) gets modified from version to version.
> See http://wix.sourceforge.net/manual-wix2/wix_xsd_product.htm

Maybe this is is something you could look into, too.

**Comment by mike-ward** [comment]
I follow the upgrade code/product code convention correctly.

The issue turns out to be a flaw in the windows installer technology. You can Google to read more about it but it comes down to the windows shell nuking pinned shortcuts when the target shortcut is removed. The installer technology removes and reinstalls shortcuts by default (even on minor upgrades). I can disable this but then uninstalls don't remove shortcuts as they should.

I've tried several workarounds as suggested in StackOverflow and other places. None of them seem to work. The solution I've settled on for the moment is to disable shortcut removal and add custom actions to remove the shortcuts only on uninstall.

I should have something for the next release.

**Comment by UweKeim** [comment]
Thank you, @mike-ward!

**Comment by mike-ward** [comment]
Note: The next update will still nuke your shortcut. Subsequent updates should not.
