### ISSUE TITLE
Keyboard shortcut / UI for links

### ISSUE THREAD

**Issue by borekb** [mike-ward/Markdown-Edit#57]
It would be nice to have some minimal GUI for entering links after the Cltr+L shortcut. This is common in most other Markdown editors (95% by a very scientific guess) and is a nice convenience feature.

Note: I know about the `link` snippet, this feature request is driven by the use case where I already have a link text written and want to "surround" it with link markup and enter the URL.

**Comment by borekb** [comment]
An idea: while other editors include some kind of popup, if you don't like popus maybe it would be enough to surround the link text with `[` nad `]()` and place the cursor where URL can be pasted.

**Comment by mike-ward** [comment]
I've considered this issue for a while. Here's my proposal.

If there's selected text and you paste a something that looks like a
link, MDE will put the selected text in brackets and the link in
parethensis (essentially create a Markdown link)

If the link is an image link same thing but with the leading bang (!) to
make it an image link.

Since `Ctrl+L` is already used for lists, `Alt+L` could trigger the
behavior you suggest with surrounding the text and locating the cursor.
If nothing is selected, it behaves like the link snippet.

I'm also occurs to me I should add a substition parameter for selections
for use in snippets ($SELECT).

**Comment by borekb** [comment]
My concern would be about muscle memory, you're suggestions are clever but maybe there is more value in smooth experience for all those StackOverflow / StackEdit / Discourse / MarkdownPad / ... users who simply are used to `Ctrl+L` bringing up a dialog to enter the URL.

All your other suggestions also sound great and would be great for power users, however, generally I would suggest reserving "standard" shortcuts for "standard" Markdown editor behavior and implementing it. My 2c.

**Comment by mike-ward** [comment]
Didn't realize `Ctrl+L` was used that way. I'll add a functionally similar to StackOverflow and wire it to `Ctrl+L`.

**Comment by mike-ward** [comment]
Fixed in 1.15

**Comment by borekb** [comment]
Just tried it and the current implementation is EX-CEL-LENT. I especially like that I can just select a text and paste the URL. I don't think any other Markdown editor has that. Thank you.

**Comment by mike-ward** [comment]
I'm not entirely happy with it yet but it's close. Keep an I on it and let me know if there are edge cases where it fails.

**Comment by borekb** [comment]
One thing I noticed is that pasting URL when having some text selected takes a bit of time, like a couple of hundreds of milliseconds. No big deal but maybe there's something making it slower than it needs to be.

**Comment by mike-ward** [comment]
OK, I'll have a look.
