### ISSUE TITLE
Editor and Preview panes syncing

### ISSUE THREAD

**Issue by seperman** [mike-ward/Markdown-Edit#89]
If I use some pictures and stuff that take one line in the editor but a good amount of space in the preview, the scroll easily gets out of sync between the tow panes, Is it possible to fix it?
Thanks

**Comment by mike-ward** [comment]
I've tried to fix that a few times but have not come up with a way to do it.

**Comment by seperman** [comment]
@mike-ward unfortunately I don't have any experience with C# to know what is going on in Markdown Edit. But in online implementations like in stackedit.io, it syncs with the line that it is in the middle of the current  page. Are you rendering the whole markdown using Pandoc into HTML right now? Can you sync with the bookmarks of H1, H2, ... in the page then?

**Comment by mike-ward** [comment]
Any solution would require scanning the generated document as you suggest. It's something I want to fix but just not a high priority at the moment.

**Comment by mike-ward** [comment]
I looked at StackEdit's sync algorithm briefly. It appears that there are extra class attributes used as anchor points. Sounds like you're familar with the algorithm. If you can explain it I'll take a shot at implementing it.

**Comment by seperman** [comment]
Honestly I'm not that familiar with the algorithm if you mean what makes it a smooth scroll to different anchors. Even if it jumps to different anchors as you move the cursor in the edit pane, that is great start. On my long documents, the preview pane is useless. It is always out of sync.

**Comment by mike-ward** [comment]
OK, I'll have to think about how to approach this issue. Not sure what I could use for anchors at this point.

**Comment by mike-ward** [comment]
I was referring to the algorithm to determine scroll position, not the smooth scroll.

I dug into how they do this and it appears they place anchors in both the source and generated output. This works for them because they gernerate a source view with HTML. MDE doesn't do this since it's a desktop editor and does not have to render source in HTML.

This makes it a much harder problem for MDE since there are no anchors to match against.

Something I'm going to try this weekend is to compute the height of the document including images. That should get very close. However, without some type of text anchor, getting spot on will be difficult. Suggestions on a strategy to deal with this are welcomed.

**Comment by mike-ward** [comment]
https://github.com/mike-ward/Markdown-Edit/commit/97de2756ba85c46acdc34c687134a22709dbc78d

**Comment by seperman** [comment]
@mike-ward Thanks for working on this. When is it going to be released compiled?

**Comment by mike-ward** [comment]
It's in version 1.21
